<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

use App\Models\Catalog;
use App\Models\CatalogType;
use App\Models\Constant;
class DatabaseSeeder extends Seeder {

/**
 * Run the database seeds.
 *
 * @return void
 */
	public function run()
	{
		Eloquent::unguard();
		
		// $this->call('UserTableSeeder');
		//Schema::dropIfExists('catalog');
		//Schema::dropIfExists('catalog_type');
		// $catalog = new CatalogTable();
		// $catalog->up();
/*
	Schema::create('catalog_type', function($table)
		{
			$table->increments('id');
			$table->string('name');
			$table->string('description');
			$table->timestamp('created_at');
			$table->timestamp('updated_at');
		});
		
		// creates table
		Schema::create('catalog', function($table)
		{
			$table->increments('id');
			$table->integer('catalog_type_id')->index();
			$table->integer('parent_id')->nullable();
			$table->string('name');
			$table->string('description');
			$table->timestamp('created_at');
			$table->timestamp('updated_at');
		});*/
		
// 		DB::table('catalog')->delete();  //  borra pero los id siguen con el numero que se quedaron por eso hago drop
// 		DB::table('catalog_type')->delete();
		

		// 	catalog type
        CatalogType::create(array('name' => 'marca bicicleta','description' => 'marca bicicleta'));//id = Constant::CATALOG_BICYCLE_BRAND_ID
        CatalogType::create(array('name' => 'marca motocicleta','description' => 'marca motocicleta'));//id = 2
        CatalogType::create(array('name' => 'modelo bicicleta','description' => 'modelo bicicleta'));//id = 3
        CatalogType::create(array('name' => 'modelo motocicleta','description' => 'modelo motocicleta'));//id = 4
		CatalogType::create(array('name' => 'tipo bicicleta','description' => 'tipo bicicleta'));//id = Constant::CATALOG_BICYCLE_TYPE_ID
		CatalogType::create(array('name' => 'tipo motocicleta','description' => 'tipo motocicleta'));//id = 6
		CatalogType::create(array('name' => 'ciudad','description' => 'ciudad')); //id = Constant::CATALOG_CITY_ID

		// 	Catalog tipo bicicleta
		Catalog::create(array('name' => 'Mountainbike(Bicicletademontaña)','description' => 'Mountainbike(Bicicletademontaña)','catalog_type_id'=>Constant::CATALOG_BICYCLE_TYPE_ID));
		Catalog::create(array('name' => 'bmx','description' => 'bmx','catalog_type_id'=>Constant::CATALOG_BICYCLE_TYPE_ID));
		Catalog::create(array('name' => 'Allmountain','description' => 'Allmountain','catalog_type_id'=>Constant::CATALOG_BICYCLE_TYPE_ID));
		Catalog::create(array('name' => 'DirtJump/Street','description' => 'DirtJump/Street','catalog_type_id'=>Constant::CATALOG_BICYCLE_TYPE_ID));
		Catalog::create(array('name' => 'Freeride','description' => 'Freeride','catalog_type_id'=>Constant::CATALOG_BICYCLE_TYPE_ID));
		Catalog::create(array('name' => 'Down Hill','description' => 'Down Hill','catalog_type_id'=>Constant::CATALOG_BICYCLE_TYPE_ID));
		Catalog::create(array('name' => 'Trial','description' => 'Trial','catalog_type_id'=>Constant::CATALOG_BICYCLE_TYPE_ID));
		Catalog::create(array('name' => 'Ruta','description' => 'Ruta','catalog_type_id'=>Constant::CATALOG_BICYCLE_TYPE_ID));
		
		//  marca bicicleta
		Catalog::create(array('name' => 'Apace','description' => 'Apace','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'AX-Lightness','description' => 'AX-Lightness','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Baum','description' => 'Baum','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Bergamont','description' => 'Bergamont','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Bionicon','description' => 'Bionicon','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Bulls','description' => 'Bulls','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Canyon','description' => 'Canyon','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Centurion','description' => 'Centurion','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Corratec','description' => 'Corratec','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Cube','description' => 'Cube','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Focus','description' => 'Focus','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Ghost','description' => 'Ghost','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Haibike','description' => 'Haibike','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Hawk','description' => 'Hawk','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Last','description' => 'Last','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Lightweight','description' => 'Lightweight','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Liteville','description' => 'Liteville','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Marcello','description' => 'Marcello','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Nicolai','description' => 'Nicolai','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Nox','description' => 'Nox','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Poison','description' => 'Poison','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Primaxi','description' => 'Primaxi','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Radon','description' => 'Radon','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Rafael','description' => 'Rafael','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Rose','description' => 'Rose','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Rotwild','description' => 'Rotwild','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Silverback','description' => 'Silverback','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Simplon','description' => 'Simplon','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Solid','description' => 'Solid','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Steppenwolf','description' => 'Steppenwolf','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Stevens','description' => 'Stevens','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Storck','description' => 'Storck','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Univega','description' => 'Univega','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Votec','description' => 'Votec','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Wiesmann','description' => 'Wiesmann','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Commençal','description' => 'Commençal','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Colner','description' => 'Colner','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Apollo','description' => 'Apollo','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Cell','description' => 'Cell','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Iride','description' => 'Iride','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'MalverStar','description' => 'MalverStar','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Airstreeem','description' => 'Airstreeem','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Kraftstoff','description' => 'Kraftstoff','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Flanders','description' => 'Flanders','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Merckx','description' => 'Merckx','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Museeuw','description' => 'Museeuw','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Ridley','description' => 'Ridley','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Ritte','description' => 'Ritte','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Viper','description' => 'Viper','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Caloi','description' => 'Caloi','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Ram','description' => 'Ram','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Shockblaze','description' => 'Shockblaze','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Vivelo','description' => 'Vivelo','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Argon18','description' => 'Argon18','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Cervélo','description' => 'Cervélo','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Cove','description' => 'Cove','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'DeVinci','description' => 'DeVinci','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Guru','description' => 'Guru','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'KindhumanLouisGarneau','description' => 'KindhumanLouisGarneau','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Norco','description' => 'Norco','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'RockyMountain','description' => 'RockyMountain','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Neilpryde','description' => 'Neilpryde','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'SwiftCarbon','description' => 'SwiftCarbon','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Principia','description' => 'Principia','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Pronghorn','description' => 'Pronghorn','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'GW','description' => 'GW','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'CTM','description' => 'CTM','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Dema','description' => 'Dema','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Kellys','description' => 'Kellys','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Berria','description' => 'Berria','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'BH','description' => 'BH','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Boamorte','description' => 'Boamorte','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'B-Pro','description' => 'B-Pro','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'CBK','description' => 'CBK','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Coluer','description' => 'Coluer','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Conor','description' => 'Conor','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Cosmos','description' => 'Cosmos','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Ditec','description' => 'Ditec','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Goka','description' => 'Goka','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Jerónimo','description' => 'Jerónimo','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Kanaola','description' => 'Kanaola','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Macario','description' => 'Macario','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Massi','description' => 'Massi','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Megamo','description' => 'Megamo','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Mendiz','description' => 'Mendiz','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Metta','description' => 'Metta','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'MMR','description' => 'MMR','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Mondraker','description' => 'Mondraker','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Monty','description' => 'Monty','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'MSC','description' => 'MSC','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Orbea','description' => 'Orbea','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Otte','description' => 'Otte','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Oxo','description' => 'Oxo','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Qüer','description' => 'Qüer','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Vitoria','description' => 'Vitoria','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Wolfbike','description' => 'Wolfbike','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Xclusive','description' => 'Xclusive','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Alchemy','description' => 'Alchemy','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Appleman','description' => 'Appleman','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Argonaut','description' => 'Argonaut','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Aventón','description' => 'Aventón','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Blue','description' => 'Blue','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Bohemian','description' => 'Bohemian','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Borealis','description' => 'Borealis','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Boo','description' => 'Boo','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Breezer','description' => 'Breezer','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Caletti','description' => 'Caletti','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Calfee','description' => 'Calfee','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Cannondale','description' => 'Cannondale','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Culprit','description' => 'Culprit','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Diamondback','description' => 'Diamondback','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Evil','description' => 'Evil','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Felt','description' => 'Felt','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Firefly','description' => 'Firefly','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'FoesRacing','description' => 'FoesRacing','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'GT','description' => 'GT','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Ibis','description' => 'Ibis','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'IF','description' => 'IF','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Intense','description' => 'Intense','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'IronHorse','description' => 'IronHorse','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Jamis','description' => 'Jamis','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Javelin','description' => 'Javelin','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'K2','description' => 'K2','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Kestrel','description' => 'Kestrel','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Kona','description' => 'Kona','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Leader','description' => 'Leader','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Litespeed','description' => 'Litespeed','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Marin','description' => 'Marin','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Maverick','description' => 'Maverick','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Mongoose','description' => 'Mongoose','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Moots','description' => 'Moots','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Motobecane','description' => 'Motobecane','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Niner','description' => 'Niner','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Nishiki','description' => 'Nishiki','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Parlee','description' => 'Parlee','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Pivot','description' => 'Pivot','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'QuintanaRoo','description' => 'QuintanaRoo','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Redline','description' => 'Redline','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'RockMachine','description' => 'RockMachine','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Salsa','description' => 'Salsa','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Sampson','description' => 'Sampson','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'SantaCruz','description' => 'SantaCruz','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Serotta','description' => 'Serotta','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Seven','description' => 'Seven','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Scott','description' => 'Scott','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Schwinn','description' => 'Schwinn','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Specialized','description' => 'Specialized','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Stijl','description' => 'Stijl','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Surly','description' => 'Surly','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Titus','description' => 'Titus','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Tomac','description' => 'Tomac','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Transition','description' => 'Transition','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Trek','description' => 'Trek','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Turner','description' => 'Turner','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Ventana','description' => 'Ventana','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Volagi','description' => 'Volagi','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Yeti','description' => 'Yeti','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'B-Twin','description' => 'B-Twin','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'CKT','description' => 'CKT','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Cyfac','description' => 'Cyfac','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Giraglia','description' => 'Giraglia','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Gitane','description' => 'Gitane','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Lapierre','description' => 'Lapierre','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'LennyJ','description' => 'LennyJ','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Look','description' => 'Look','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Sunn','description' => 'Sunn','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Time','description' => 'Time','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Vitus','description' => 'Vitus','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Aprire','description' => 'Aprire','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Beacon','description' => 'Beacon','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Brompton','description' => 'Brompton','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Boardman','description' => 'Boardman','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Condor','description' => 'Condor','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Craddock','description' => 'Craddock','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'DMR','description' => 'DMR','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Dolan','description' => 'Dolan','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Enigma','description' => 'Enigma','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Forme','description' => 'Forme','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Genesis','description' => 'Genesis','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Hoy','description' => 'Hoy','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Identiti','description' => 'Identiti','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Kinesis','description' => 'Kinesis','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'LeeCougan','description' => 'LeeCougan','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Mekk','description' => 'Mekk','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Merlin','description' => 'Merlin','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Moda','description' => 'Moda','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Nukeproof','description' => 'Nukeproof','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Orange','description' => 'Orange','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Pearson','description' => 'Pearson','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Pinnacle','description' => 'Pinnacle','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'PlanetX','description' => 'PlanetX','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Raleigh','description' => 'Raleigh','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Ribble','description' => 'Ribble','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Saracen','description' => 'Saracen','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Singular','description' => 'Singular','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Starley','description' => 'Starley','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Tifosi','description' => 'Tifosi','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Trigon','description' => 'Trigon','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Verenti','description' => 'Verenti','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Whyte','description' => 'Whyte','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Windymilla','description' => 'Windymilla','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Ballistic','description' => 'Ballistic','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Ideal','description' => 'Ideal','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Airborne','description' => 'Airborne','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'BeOne','description' => 'BeOne','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Duell','description' => 'Duell','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Isaac','description' => 'Isaac','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Koga','description' => 'Koga','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Moozes','description' => 'Moozes','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Sensa','description' => 'Sensa','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'VanNicholas','description' => 'VanNicholas','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Zannata','description' => 'Zannata','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Adriatica','description' => 'Adriatica','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Alan','description' => 'Alan','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Basso','description' => 'Basso','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Battaglin','description' => 'Battaglin','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Bianchi','description' => 'Bianchi','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Botecchia','description' => 'Botecchia','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Caam','description' => 'Caam','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Carraro','description' => 'Carraro','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Carrera','description' => 'Carrera','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Casati','description' => 'Casati','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Cinelli','description' => 'Cinelli','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Ciocc','description' => 'Ciocc','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Cipollini','description' => 'Cipollini','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Colnago','description' => 'Colnago','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Coppi','description' => 'Coppi','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Dedacciai','description' => 'Dedacciai','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'DeRosa','description' => 'DeRosa','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Dynatek','description' => 'Dynatek','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Fabike','description' => 'Fabike','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Fondriest','description' => 'Fondriest','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Formigli','description' => 'Formigli','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'FRM','description' => 'FRM','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Gios','description' => 'Gios','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Guerciotti','description' => 'Guerciotti','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Kuota','description' => 'Kuota','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Lombardo','description' => 'Lombardo','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Marchisio','description' => 'Marchisio','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Moser','description' => 'Moser','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Olmo','description' => 'Olmo','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Olympia','description' => 'Olympia','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Opera','description' => 'Opera','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Pantani','description' => 'Pantani','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Parkpre','description' => 'Parkpre','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Passoni','description' => 'Passoni','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Pinarello','description' => 'Pinarello','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Sarto','description' => 'Sarto','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Scappa','description' => 'Scappa','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Scapin','description' => 'Scapin','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Sintesi','description' => 'Sintesi','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Somec','description' => 'Somec','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Tommasini','description' => 'Tommasini','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Torpado','description' => 'Torpado','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Venettella','description' => 'Venettella','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Viner','description' => 'Viner','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Whistle','description' => 'Whistle','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Wilier','description' => 'Wilier','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Anchor(Bridgestone)','description' => 'Anchor(Bridgestone)','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Ceepo','description' => 'Ceepo','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Fuji','description' => 'Fuji','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Kalavinka','description' => 'Kalavinka','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Nakamura','description' => 'Nakamura','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Kompressor','description' => 'Kompressor','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Alubike','description' => 'Alubike','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Benotto','description' => 'Benotto','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Magistroni','description' => 'Magistroni','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Mercurio','description' => 'Mercurio','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Turbo','description' => 'Turbo','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Veloci','description' => 'Veloci','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'DBS','description' => 'DBS','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Avanti','description' => 'Avanti','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Duncon','description' => 'Duncon','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Kross','description' => 'Kross','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Banshee','description' => 'Banshee','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Berg','description' => 'Berg','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Duratec','description' => 'Duratec','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'VanNicholas','description' => 'VanNicholas','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'NSR','description' => 'NSR','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Morewood','description' => 'Morewood','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Alpcross','description' => 'Alpcross','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'BMC','description' => 'BMC','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Axman','description' => 'Axman','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Giant','description' => 'Giant','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'KHS','description' => 'KHS','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Matrix','description' => 'Matrix','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Merida','description' => 'Merida','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Monoc','description' => 'Monoc','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Speedone','description' => 'Speedone','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Token','description' => 'Token','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Wheeler','description' => 'Wheeler','catalog_type_id'=>Constant::CATALOG_BICYCLE_BRAND_ID));
		
		// Catalogo ciudades
		Catalog::create(array('name' => 'Guayaquil','description' => 'Guayaquil','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Quito','description' => 'Quito','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Cuenca','description' => 'Cuenca','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Santo Domingo','description' => 'Santo Domingo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Machala','description' => 'Machala','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Durán','description' => 'Durán','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Manta','description' => 'Manta','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Portoviejo','description' => 'Portoviejo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Loja','description' => 'Loja','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Ambato','description' => 'Ambato','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Esmeraldas','description' => 'Esmeraldas','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Quevedo','description' => 'Quevedo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Riobamba','description' => 'Riobamba','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Milagro','description' => 'Milagro','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Ibarra','description' => 'Ibarra','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Libertad','description' => 'Libertad','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Babahoyo','description' => 'Babahoyo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Sangolquí','description' => 'Sangolquí','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Daule','description' => 'Daule','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Latacunga','description' => 'Latacunga','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Tulcán','description' => 'Tulcán','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Chone','description' => 'Chone','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Pasaje','description' => 'Pasaje','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Santa Rosa','description' => 'Santa Rosa','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Loja','description' => 'Loja','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Huaquillas','description' => 'Huaquillas','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'El Carmen','description' => 'El Carmen','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Montecristi','description' => 'Montecristi','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Samborondón','description' => 'Samborondón','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Orellana','description' => 'Orellana','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Jipijapa','description' => 'Jipijapa','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Santa Elena','description' => 'Santa Elena','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Otavalo','description' => 'Otavalo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Cayambe','description' => 'Cayambe','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Buena Fe','description' => 'Buena Fe','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Ventanas','description' => 'Ventanas','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Velasco Ibarra','description' => 'Velasco Ibarra','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'La Troncal','description' => 'La Troncal','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'El Triunfo','description' => 'El Triunfo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Salinas','description' => 'Salinas','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Playas','description' => 'Playas','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Azogues','description' => 'Azogues','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Puyo','description' => 'Puyo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Vinces','description' => 'Vinces','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'La Concordia','description' => 'La Concordia','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Quinindé','description' => 'Quinindé','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Balzar','description' => 'Balzar','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Naranjito','description' => 'Naranjito','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Naranjal','description' => 'Naranjal','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Guaranda','description' => 'Guaranda','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'La Maná','description' => 'La Maná','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Tena','description' => 'Tena','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'San Lorenzo','description' => 'San Lorenzo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Catamayo','description' => 'Catamayo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'El Guabo','description' => 'El Guabo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Pedernales','description' => 'Pedernales','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Atuntaqui','description' => 'Atuntaqui','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Bahía de Caráquez','description' => 'Bahía de Caráquez','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Pedro Carbo','description' => 'Pedro Carbo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Macas','description' => 'Macas','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Yaguachi','description' => 'Yaguachi','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Calceta','description' => 'Calceta','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Arenillas','description' => 'Arenillas','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Jaramijó','description' => 'Jaramijó','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Valencia','description' => 'Valencia','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Machachi','description' => 'Machachi','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Shushufindi','description' => 'Shushufindi','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Atacames','description' => 'Atacames','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Piñas','description' => 'Piñas','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'San Gabriel','description' => 'San Gabriel','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Gualaceo','description' => 'Gualaceo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Cañar','description' => 'Cañar','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Cariamanga','description' => 'Cariamanga','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Baños','description' => 'Baños','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Montalvo','description' => 'Montalvo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Macará','description' => 'Macará','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Salcedo','description' => 'Salcedo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Zamora','description' => 'Zamora','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Puerto Ayora','description' => 'Puerto Ayora','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'La Joya de los Sachas','description' => 'La Joya de los Sachas','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Salitre','description' => 'Salitre','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Pelileo','description' => 'Pelileo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Pujilí','description' => 'Pujilí','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Tabacundo','description' => 'Tabacundo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Puerto López','description' => 'Puerto López','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'San Vicente','description' => 'San Vicente','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Santa Ana','description' => 'Santa Ana','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Zaruma','description' => 'Zaruma','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Balao','description' => 'Balao','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Rocafuerte','description' => 'Rocafuerte','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Yantzaza','description' => 'Yantzaza','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Cotacachi','description' => 'Cotacachi','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Santa Lucía','description' => 'Santa Lucía','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Cumandá','description' => 'Cumandá','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Palestina','description' => 'Palestina','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Jujan','description' => 'Jujan','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Nobol','description' => 'Nobol','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Mocache','description' => 'Mocache','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Puebloviejo','description' => 'Puebloviejo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Portovelo','description' => 'Portovelo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Sucúa','description' => 'Sucúa','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Guano','description' => 'Guano','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Píllaro','description' => 'Píllaro','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Simón Bolívar','description' => 'Simón Bolívar','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Gualaquiza','description' => 'Gualaquiza','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Paute','description' => 'Paute','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Saquisilí','description' => 'Saquisilí','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Coronel Marcelino Maridueña','description' => 'Coronel Marcelino Maridueña','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Paján','description' => 'Paján','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'San Miguel','description' => 'San Miguel','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Puerto Baquerizo Moreno','description' => 'Puerto Baquerizo Moreno','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Catacocha','description' => 'Catacocha','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Palenque','description' => 'Palenque','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Alausí','description' => 'Alausí','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Caluma','description' => 'Caluma','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Catarama','description' => 'Catarama','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Flavio Alfaro','description' => 'Flavio Alfaro','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Colimes','description' => 'Colimes','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Echeandía','description' => 'Echeandía','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Jama','description' => 'Jama','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Bucay','description' => 'Bucay','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Isidro Ayora','description' => 'Isidro Ayora','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Muisne','description' => 'Muisne','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Santa Isabel','description' => 'Santa Isabel','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Pedro Vicente Maldonado','description' => 'Pedro Vicente Maldonado','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Biblián','description' => 'Biblián','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Archidona','description' => 'Archidona','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Junín','description' => 'Junín','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Baba','description' => 'Baba','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Limones','description' => 'Limones','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Pimampiro','description' => 'Pimampiro','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Camilo Ponce Enríquez','description' => 'Camilo Ponce Enríquez','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'San Miguel de Los Bancos','description' => 'San Miguel de Los Bancos','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'El Tambo','description' => 'El Tambo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Quinsaloma','description' => 'Quinsaloma','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'El Ángel','description' => 'El Ángel','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Alamor','description' => 'Alamor','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Chambo','description' => 'Chambo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Chimbo','description' => 'Chimbo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Celica','description' => 'Celica','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Chordeleg','description' => 'Chordeleg','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Balsas','description' => 'Balsas','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Saraguro','description' => 'Saraguro','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'El Chaco','description' => 'El Chaco','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Girón','description' => 'Girón','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Huaca','description' => 'Huaca','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Pichincha','description' => 'Pichincha','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Chunchi','description' => 'Chunchi','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Pallatanga','description' => 'Pallatanga','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Marcabelí','description' => 'Marcabelí','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Sígsig','description' => 'Sígsig','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'General Leonidas Plaza Gutiérrez','description' => 'General Leonidas Plaza Gutiérrez','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'San Miguel de Urcuquí','description' => 'San Miguel de Urcuquí','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Loreto','description' => 'Loreto','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Rio verde','description' => 'Rio verde','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Zumba','description' => 'Zumba','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Palora','description' => 'Palora','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Mira','description' => 'Mira','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'El Pangui','description' => 'El Pangui','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Puerto Quito','description' => 'Puerto Quito','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Bolívar','description' => 'Bolívar','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Sucre','description' => 'Sucre','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Chillanes','description' => 'Chillanes','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Quero','description' => 'Quero','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Guamote','description' => 'Guamote','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Cevallos','description' => 'Cevallos','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Zapotillo','description' => 'Zapotillo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Santiago de Méndez','description' => 'Santiago de Méndez','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Zumbi','description' => 'Zumbi','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Putumayo','description' => 'Putumayo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Patate','description' => 'Patate','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Olmedo (Manabí)','description' => 'Olmedo (Manabí)','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Isabela.png Puerto Villamil','description' => 'Isabela.png Puerto Villamil','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'El Dorado de Cascales','description' => 'El Dorado de Cascales','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Lumbaqui','description' => 'Lumbaqui','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Palanda','description' => 'Palanda','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Sigchos','description' => 'Sigchos','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Pindal','description' => 'Pindal','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Guayzimi','description' => 'Guayzimi','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Baeza','description' => 'Baeza','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'El Corazón','description' => 'El Corazón','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Pacha','description' => 'Pacha','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Amaluza','description' => 'Amaluza','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Las Naves','description' => 'Las Naves','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Logroño','description' => 'Logroño','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'San Fernando','description' => 'San Fernando','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Gonzanamá','description' => 'Gonzanamá','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'San Juan Bosco','description' => 'San Juan Bosco','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Yacuambi','description' => 'Yacuambi','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Santa Clara','description' => 'Santa Clara','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Arajuno','description' => 'Arajuno','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Tarapoa','description' => 'Tarapoa','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Tisaleo','description' => 'Tisaleo','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Suscal','description' => 'Suscal','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Nabón','description' => 'Nabón','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Mocha','description' => 'Mocha','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'La Victoria','description' => 'La Victoria','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Guachapala','description' => 'Guachapala','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Santiago','description' => 'Santiago','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Chaguarpamba','description' => 'Chaguarpamba','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Penipe','description' => 'Penipe','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Taisha','description' => 'Taisha','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Chilla','description' => 'Chilla','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Paquisha','description' => 'Paquisha','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Carlos Julio Arosemena Tola','description' => 'Carlos Julio Arosemena Tola','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Sozoranga','description' => 'Sozoranga','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Pucará','description' => 'Pucará','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Huamboya','description' => 'Huamboya','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Quilanga','description' => 'Quilanga','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Sevilla de Oro','description' => 'Sevilla de Oro','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Mera','description' => 'Mera','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Pablo Sexto','description' => 'Pablo Sexto','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Olmedo (Loja)','description' => 'Olmedo (Loja)','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Déleg','description' => 'Déleg','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Sucumbíos (La Bonita)','description' => 'Sucumbíos (La Bonita)','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'El Pan','description' => 'El Pan','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		Catalog::create(array('name' => 'Nuevo Rocafuerte','description' => 'Nuevo Rocafuerte','catalog_type_id'=>Constant::CATALOG_CITY_ID));
		

		Catalog::create(array('name' => 'Motomel','description' => 'Motomel','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Zanella','description' => 'Zanella','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Siambretta','description' => 'Siambretta','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Husaberg','description' => 'Husaberg','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'KTM','description' => 'KTM','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Puch','description' => 'Puch','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Atlas','description' => 'Atlas Bangladesh Ltd.','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Walton','description' => 'Walton Hi-Tech Industries Ltd.','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'RUNNER','description' => 'RUNNER Automobiles Ltd','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Singer','description' => 'Singer Bangladesh Limited.','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Karnaphuli','description' => 'Karnaphuli Industries(Haojue motorcycles of China).','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Minsk','description' => 'Minsk','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Agrale','description' => 'Agrale','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Brasil & Movimento','description' => 'Brasil & Movimento','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Qingqi','description' => 'Qingqi','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Jincheng ','description' => 'Jincheng Suzuki','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Lifan','description' => 'Lifan','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Zongshen','description' => 'Zongshen','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Loncin','description' => 'Loncin','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Thumpstar','description' => 'Thumpstar','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'AKT','description' => 'AKT','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'CZ','description' => 'CZ','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Jawa','description' => 'Jawa','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Blata','description' => 'Blata','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Gima','description' => 'Gima','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Matra','description' => 'Matra','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Peugeot','description' => 'Peugeot','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Scorpa','description' => 'Scorpa','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Sherco','description' => 'Sherco','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Solex','description' => 'Solex','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'BMW','description' => 'BMW','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Horex','description' => 'Horex','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'MZ','description' => 'MZ','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Sachs','description' => 'Sachs','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Zundapp','description' => 'Zundapp','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'YMC','description' => 'YMC','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Bajaj','description' => 'Bajaj Auto','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'LML','description' => 'LML','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Mahindra','description' => 'Mahindra & Mahindra Limited','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'TVS Motor','description' => 'TVS Motor','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Royal Enfield (India)','description' => 'Royal Enfield (India)','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Aprilia','description' => 'Aprilia','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Benelli','description' => 'Benelli','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Beta Motor','description' => 'Beta Motor','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Bimota','description' => 'Bimota','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Borile','description' => 'Borile','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Cagiva','description' => 'Cagiva','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Ducati','description' => 'Ducati','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Fantic Motor','description' => 'Fantic Motor','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Ghezzi & Brian','description' => 'Ghezzi & Brian','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Gilera','description' => 'Gilera','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Italjet','description' => 'Italjet','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Malaguti','description' => 'Malaguti','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Minarelli','description' => 'Minarelli','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Mondial','description' => 'Mondial','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Husqvarna','description' => 'Husqvarna','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Motobi','description' => 'Motobi','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Moto Guzzi','description' => 'Moto Guzzi','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Moto Morini','description' => 'Moto Morini','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'MV Agusta','description' => 'MV Agusta','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Paton','description' => 'Paton','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Piaggio','description' => 'Piaggio','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Terra Modena','description' => 'Terra Modena','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Vyrus','description' => 'Vyrus','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Kawasaki','description' => 'Kawasaki','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Suzuki','description' => 'Suzuki','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Yamaha','description' => 'Yamaha','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Daelim','description' => 'Daelim','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'S&T','description' => 'S&T','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Hyosung','description' => 'Hyosung','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Modenas','description' => 'Modenas','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Italika','description' => 'Italika','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Bahawalpur Motors Limited','description' => 'Bahawalpur Motors Limited','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Ghani Automobile Industries','description' => 'Ghani Automobile Industries','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Honda','description' => 'Honda','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Hamza','description' => 'Hamza','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'AJP','description' => 'AJP','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Aliança','description' => 'Aliança','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Casal','description' => 'Casal','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Conquistador','description' => 'Conquistador','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Dural','description' => 'Dural','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'FAMEL','description' => 'FAMEL','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'IMZ-Ural','description' => 'IMZ-Ural','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'IZh','description' => 'IZh','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Tomos','description' => 'Tomos','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Bultaco','description' => 'Bultaco','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Derbi','description' => 'Derbi','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Montesa','description' => 'Montesa','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Ossa','description' => 'Ossa','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Rieju','description' => 'Rieju','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Sanglas','description' => 'Sanglas','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Kymco','description' => 'Kymco','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'SYM','description' => 'SYM','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Hartford','description' => 'Hartford','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Kanuni','description' => 'Kanuni','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Clews Competition Motorcycles','description' => 'Clews Competition Motorcycles','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Matchless','description' => 'Matchless','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Megelli','description' => 'Megelli Motorcycles','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Norton','description' => 'Norton','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Rickman','description' => 'Rickman','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Triumph','description' => 'Triumph','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Alligator','description' => 'Alligator','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Arlen Ness','description' => 'Arlen Ness','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'ATK motorcycles','description' => 'ATK motorcycles','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Boss Hoss','description' => 'Boss Hoss','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Brammo','description' => 'Brammo','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Cleveland CycleWerks','description' => 'Cleveland CycleWerks','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Confederate Motorcycles','description' => 'Confederate Motorcycles','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Erik Buell Racing','description' => 'Erik Buell Racing','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Fischer','description' => 'Fischer','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Harley-Davidson','description' => 'Harley-Davidson','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Indian','description' => 'Indian','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Janus Motorcycles','description' => 'Janus Motorcycles','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'MTT','description' => 'MTT','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'MotoCzysz','description' => 'MotoCzysz','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Motus','description' => 'Motus','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Roehr Motorcycles','description' => 'Roehr Motorcycles','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Rokon','description' => 'Rokon','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Titan','description' => 'Titan','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Victory','description' => 'Victory','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Whizzer','description' => 'Whizzer','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		Catalog::create(array('name' => 'Gas Gas','description' => 'Gas Gas','catalog_type_id'=>Constant::CATALOG_MOTORCYCLE_BRAND_ID));
		
		// catalog motorcycle types
		Catalog::create(array('name' => 'Chopper','description' => 'Chopper','catalog_type_id'=>Constant::CATALOG_MOTO_TYPE_ID ));
		Catalog::create(array('name' => 'Ciclomotor','description' => 'Ciclomotor','catalog_type_id'=>Constant::CATALOG_MOTO_TYPE_ID ));
		Catalog::create(array('name' => 'Scooter - Pasola','description' => 'Scooter - Pasola','catalog_type_id'=>Constant::CATALOG_MOTO_TYPE_ID ));
		Catalog::create(array('name' => 'Cross','description' => 'Cross','catalog_type_id'=>Constant::CATALOG_MOTO_TYPE_ID ));
		Catalog::create(array('name' => 'Custom','description' => 'Custom','catalog_type_id'=>Constant::CATALOG_MOTO_TYPE_ID ));
		Catalog::create(array('name' => 'Deportiva','description' => 'Deportiva','catalog_type_id'=>Constant::CATALOG_MOTO_TYPE_ID ));
		Catalog::create(array('name' => 'Eléctrica','description' => 'Eléctrica','catalog_type_id'=>Constant::CATALOG_MOTO_TYPE_ID ));
		Catalog::create(array('name' => 'Minimoto','description' => 'Minimoto','catalog_type_id'=>Constant::CATALOG_MOTO_TYPE_ID ));
		Catalog::create(array('name' => 'Mobylette','description' => 'Mobylette','catalog_type_id'=>Constant::CATALOG_MOTO_TYPE_ID ));
		Catalog::create(array('name' => 'Enduro','description' => 'Enduro','catalog_type_id'=>Constant::CATALOG_MOTO_TYPE_ID ));
		Catalog::create(array('name' => 'Mototaxi','description' => 'Mototaxi','catalog_type_id'=>Constant::CATALOG_MOTO_TYPE_ID ));
		Catalog::create(array('name' => 'Sidecar','description' => 'Sidecar','catalog_type_id'=>Constant::CATALOG_MOTO_TYPE_ID ));
		Catalog::create(array('name' => 'Streetfighter (motocicleta)','description' => 'Streetfighter (motocicleta)','catalog_type_id'=>Constant::CATALOG_MOTO_TYPE_ID ));
		Catalog::create(array('name' => 'Trial','description' => 'Trial','catalog_type_id'=>Constant::CATALOG_MOTO_TYPE_ID ));
				
		
		
		
		
	}

}